#!/bin/bash

set -euo pipefail

if ! command -v starship > /dev/null ; then
  curl -sS https://starship.rs/install.sh | sh -s -- --yes
fi

# use zsh as default shell
if command -v zsh > /dev/null ; then
  sudo chsh -s $(command -v zsh) $USER
fi

# install chezmoi and pull dotfiles from GitHub
if ! command -v chezmoi > /dev/null ; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:diraulo/dotfiles-devcontainers.git
fi

exit 0
