[tools]
bat = "latest"
chezmoi = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"    #  required for mise completion
go = "latest"
